---
title: "117th U.S Congress & Member Ideology"
author: "Osazi AL KHaliq"
description: "How responsive is the 117th U.S Congress to the districts/states it represents?"
output:
  distill::distill_article:
    self_contained: false
---


## Project thoughts

I am interested in exploring data related to Presidential Elections and Residential Mortgage Performance. Politicians eagerly use the health of the mortgage market and the overall economy as an indicator of party performance. This party performance becomes an important voting issue during elections. My project will ask whether Mortgage performance trends has a relationship with Presidential elections.

To investigate this relationship, we are relying on data from two different sources:

1. [U.S. President Election Data 1976-2020](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/42MVDX) This data file contains constituency (state-level) returns for elections to the U.S. presidency from 1976 to 2020;

2. [Residential Mortgage Performance Statistics](https://www.fhfa.gov/DataTools/Downloads/Pages/National-Mortgage-Database-Aggregate-Data.aspx) This data file contains a nationally representative five percent sample of residential mortgages in the United States

The Election data provides us with our outcome variable, the residential mortgage performance (along All Geographic Areas, States, 100 Metro Areas, and National, Census Regions, and Census Divisions) acts as the explanatory variable.

